version:  '3.7'
services:
  mysql_db:
    image: mariadb
    restart: always
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - './docker/database:/var/lib/mysql:cached'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    volumes:
      - './docker/php/config/php_phpmyadmin.ini:/usr/local/etc/php/conf.d/php.ini'
    ports:
      - '${PHPMYADMIN_PORT}:80'

  nginx:
    image: nginx:1.15.3-alpine
    restart: always
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - './:/usr/src/app:cached'
      - './docker/composer/:/.composer'
      - './docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini'

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "${MAILCATCHER_PORT}:1080"